// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: accounts.sql

package database

import (
	"context"
)

const createAccount = `-- name: CreateAccount :exec
INSERT INTO accounts (
    id,
    user_id,
    balance,
    currency
)
VALUES (?, ?, ?, ?)
`

type CreateAccountParams struct {
	ID       string `json:"id"`
	UserID   string `json:"user_id"`
	Balance  string `json:"balance"`
	Currency string `json:"currency"`
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) error {
	_, err := q.db.ExecContext(ctx, createAccount,
		arg.ID,
		arg.UserID,
		arg.Balance,
		arg.Currency,
	)
	return err
}

const getAccountByUserID = `-- name: GetAccountByUserID :one
SELECT
    id,
    user_id,
    balance,
    currency,
    created_at
FROM accounts
WHERE user_id = ?
`

func (q *Queries) GetAccountByUserID(ctx context.Context, userID string) (Account, error) {
	row := q.db.QueryRowContext(ctx, getAccountByUserID, userID)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Balance,
		&i.Currency,
		&i.CreatedAt,
	)
	return i, err
}
