// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: executions.sql

package database

import (
	"context"
)

const createExecution = `-- name: CreateExecution :exec
INSERT INTO executions (
    id,
    order_id,
    account_id,
    instrument_id,
    quantity,
    price
)
VALUES (?, ?, ?, ?, ?, ?)
`

type CreateExecutionParams struct {
	ID           string `json:"id"`
	OrderID      string `json:"order_id"`
	AccountID    string `json:"account_id"`
	InstrumentID string `json:"instrument_id"`
	Quantity     string `json:"quantity"`
	Price        string `json:"price"`
}

func (q *Queries) CreateExecution(ctx context.Context, arg CreateExecutionParams) error {
	_, err := q.db.ExecContext(ctx, createExecution,
		arg.ID,
		arg.OrderID,
		arg.AccountID,
		arg.InstrumentID,
		arg.Quantity,
		arg.Price,
	)
	return err
}

const listExecutionsByAccountID = `-- name: ListExecutionsByAccountID :many
SELECT
    id,
    order_id,
    account_id,
    instrument_id,
    quantity,
    price,
    executed_at
FROM executions
WHERE account_id = ?
ORDER BY executed_at DESC
`

func (q *Queries) ListExecutionsByAccountID(ctx context.Context, accountID string) ([]Execution, error) {
	rows, err := q.db.QueryContext(ctx, listExecutionsByAccountID, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Execution
	for rows.Next() {
		var i Execution
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.AccountID,
			&i.InstrumentID,
			&i.Quantity,
			&i.Price,
			&i.ExecutedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
