// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: instruments.sql

package database

import (
	"context"
)

const createInstrument = `-- name: CreateInstrument :exec
INSERT INTO instruments  (
    id,
    symbol,
    name,
    type,
    currency
)
VALUES (?, ?, ?, ?, ?)
`

type CreateInstrumentParams struct {
	ID       string `json:"id"`
	Symbol   string `json:"symbol"`
	Name     string `json:"name"`
	Type     string `json:"type"`
	Currency string `json:"currency"`
}

func (q *Queries) CreateInstrument(ctx context.Context, arg CreateInstrumentParams) error {
	_, err := q.db.ExecContext(ctx, createInstrument,
		arg.ID,
		arg.Symbol,
		arg.Name,
		arg.Type,
		arg.Currency,
	)
	return err
}

const getInstrumentByID = `-- name: GetInstrumentByID :one
SELECT
    id,
    symbol,
    name,
    type,
    currency,
    created_at
FROM instruments
WHERE id = ?
`

func (q *Queries) GetInstrumentByID(ctx context.Context, id string) (Instrument, error) {
	row := q.db.QueryRowContext(ctx, getInstrumentByID, id)
	var i Instrument
	err := row.Scan(
		&i.ID,
		&i.Symbol,
		&i.Name,
		&i.Type,
		&i.Currency,
		&i.CreatedAt,
	)
	return i, err
}

const getInstrumentBySymbol = `-- name: GetInstrumentBySymbol :one
SELECT
    id,
    symbol,
    name,
    type,
    currency,
    created_at
FROM instruments
WHERE symbol = ?
`

func (q *Queries) GetInstrumentBySymbol(ctx context.Context, symbol string) (Instrument, error) {
	row := q.db.QueryRowContext(ctx, getInstrumentBySymbol, symbol)
	var i Instrument
	err := row.Scan(
		&i.ID,
		&i.Symbol,
		&i.Name,
		&i.Type,
		&i.Currency,
		&i.CreatedAt,
	)
	return i, err
}

const listInstruments = `-- name: ListInstruments :many
SELECT
    id,
    symbol,
    name,
    type,
    currency,
    created_at
FROM instruments
ORDER BY symbol
`

func (q *Queries) ListInstruments(ctx context.Context) ([]Instrument, error) {
	rows, err := q.db.QueryContext(ctx, listInstruments)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Instrument
	for rows.Next() {
		var i Instrument
		if err := rows.Scan(
			&i.ID,
			&i.Symbol,
			&i.Name,
			&i.Type,
			&i.Currency,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
