// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Account struct {
	ID              string    `json:"id"`
	UserID          string    `json:"user_id"`
	Balance         string    `json:"balance"`
	Currency        string    `json:"currency"`
	CreatedAt       time.Time `json:"created_at"`
	ReservedBalance string    `json:"reserved_balance"`
}

type Instrument struct {
	ID        string    `json:"id"`
	Symbol    string    `json:"symbol"`
	Name      string    `json:"name"`
	Type      string    `json:"type"`
	Currency  string    `json:"currency"`
	CreatedAt time.Time `json:"created_at"`
}

type Order struct {
	ID           string         `json:"id"`
	AccountID    string         `json:"account_id"`
	InstrumentID string         `json:"instrument_id"`
	Side         string         `json:"side"`
	Type         string         `json:"type"`
	Quantity     string         `json:"quantity"`
	Price        sql.NullString `json:"price"`
	Status       string         `json:"status"`
	CreatedAt    time.Time      `json:"created_at"`
}

type Position struct {
	ID               string    `json:"id"`
	AccountID        string    `json:"account_id"`
	InstrumentID     string    `json:"instrument_id"`
	Quantity         string    `json:"quantity"`
	AveragePrice     string    `json:"average_price"`
	CreatedAt        time.Time `json:"created_at"`
	ReservedQuantity string    `json:"reserved_quantity"`
}

type User struct {
	Email        string    `json:"email"`
	PasswordHash string    `json:"password_hash"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
	ID           uuid.UUID `json:"id"`
}
