// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: orders.sql

package database

import (
	"context"
	"database/sql"
)

const createOrder = `-- name: CreateOrder :exec
INSERT INTO orders (
    id,
    account_id,
    instrument_id,
    side,
    type,
    quantity,
    price,
    status
)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateOrderParams struct {
	ID           string         `json:"id"`
	AccountID    string         `json:"account_id"`
	InstrumentID string         `json:"instrument_id"`
	Side         string         `json:"side"`
	Type         string         `json:"type"`
	Quantity     string         `json:"quantity"`
	Price        sql.NullString `json:"price"`
	Status       string         `json:"status"`
}

func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) error {
	_, err := q.db.ExecContext(ctx, createOrder,
		arg.ID,
		arg.AccountID,
		arg.InstrumentID,
		arg.Side,
		arg.Type,
		arg.Quantity,
		arg.Price,
		arg.Status,
	)
	return err
}

const getOrderByID = `-- name: GetOrderByID :one
SELECT
    id,
    account_id,
    instrument_id,
    side,
    type,
    quantity,
    price,
    status,
    created_at
FROM orders
WHERE id = ?
`

func (q *Queries) GetOrderByID(ctx context.Context, id string) (Order, error) {
	row := q.db.QueryRowContext(ctx, getOrderByID, id)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.InstrumentID,
		&i.Side,
		&i.Type,
		&i.Quantity,
		&i.Price,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const listOrdersByAccountID = `-- name: ListOrdersByAccountID :many
SELECT
    id,
    account_id,
    instrument_id,
    side,
    type,
    quantity,
    price,
    status,
    created_at
FROM orders
WHERE account_id = ?
ORDER BY created_at DESC
`

func (q *Queries) ListOrdersByAccountID(ctx context.Context, accountID string) ([]Order, error) {
	rows, err := q.db.QueryContext(ctx, listOrdersByAccountID, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Order
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.InstrumentID,
			&i.Side,
			&i.Type,
			&i.Quantity,
			&i.Price,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
