// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: orders.sql

package database

import (
	"context"
	"database/sql"
)

const cancelOrder = `-- name: CancelOrder :exec
UPDATE orders
SET status = 'CANCELED'
WHERE id = ?
    AND account_id = ?
    AND status = 'PENDING'
`

type CancelOrderParams struct {
	ID        string `json:"id"`
	AccountID string `json:"account_id"`
}

func (q *Queries) CancelOrder(ctx context.Context, arg CancelOrderParams) error {
	_, err := q.db.ExecContext(ctx, cancelOrder, arg.ID, arg.AccountID)
	return err
}

const createOrder = `-- name: CreateOrder :exec
INSERT INTO orders (
    id,
    account_id,
    instrument_id,
    side,
    type,
    quantity,
    price,
    status
)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateOrderParams struct {
	ID           string         `json:"id"`
	AccountID    string         `json:"account_id"`
	InstrumentID string         `json:"instrument_id"`
	Side         string         `json:"side"`
	Type         string         `json:"type"`
	Quantity     string         `json:"quantity"`
	Price        sql.NullString `json:"price"`
	Status       string         `json:"status"`
}

func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) error {
	_, err := q.db.ExecContext(ctx, createOrder,
		arg.ID,
		arg.AccountID,
		arg.InstrumentID,
		arg.Side,
		arg.Type,
		arg.Quantity,
		arg.Price,
		arg.Status,
	)
	return err
}

const executeOrder = `-- name: ExecuteOrder :execresult
UPDATE orders
SET status = 'EXECUTED'
WHERE id = ?
    AND account_id = ?
    AND status = 'PENDING'
`

type ExecuteOrderParams struct {
	ID        string `json:"id"`
	AccountID string `json:"account_id"`
}

func (q *Queries) ExecuteOrder(ctx context.Context, arg ExecuteOrderParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, executeOrder, arg.ID, arg.AccountID)
}

const findMatchingBuyOrder = `-- name: FindMatchingBuyOrder :one
SELECT id, account_id, instrument_id, side, type, quantity, price, status, created_at, filled_quantity
FROM orders
WHERE instrument_id = ?
  AND side = 'BUY'
  AND status = 'PENDING'
  AND price >= ?
  AND quantity > filled_quantity
ORDER BY price DESC, created_at ASC
LIMIT 1
`

type FindMatchingBuyOrderParams struct {
	InstrumentID string         `json:"instrument_id"`
	Price        sql.NullString `json:"price"`
}

func (q *Queries) FindMatchingBuyOrder(ctx context.Context, arg FindMatchingBuyOrderParams) (Order, error) {
	row := q.db.QueryRowContext(ctx, findMatchingBuyOrder, arg.InstrumentID, arg.Price)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.InstrumentID,
		&i.Side,
		&i.Type,
		&i.Quantity,
		&i.Price,
		&i.Status,
		&i.CreatedAt,
		&i.FilledQuantity,
	)
	return i, err
}

const findMatchingSellOrder = `-- name: FindMatchingSellOrder :one
SELECT id, account_id, instrument_id, side, type, quantity, price, status, created_at, filled_quantity
FROM orders
WHERE instrument_id = ?
  AND side = 'SELL'
  AND status = 'PENDING'
  AND price <= ?
  AND quantity > filled_quantity
ORDER BY price ASC, created_at ASC
LIMIT 1
`

type FindMatchingSellOrderParams struct {
	InstrumentID string         `json:"instrument_id"`
	Price        sql.NullString `json:"price"`
}

func (q *Queries) FindMatchingSellOrder(ctx context.Context, arg FindMatchingSellOrderParams) (Order, error) {
	row := q.db.QueryRowContext(ctx, findMatchingSellOrder, arg.InstrumentID, arg.Price)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.InstrumentID,
		&i.Side,
		&i.Type,
		&i.Quantity,
		&i.Price,
		&i.Status,
		&i.CreatedAt,
		&i.FilledQuantity,
	)
	return i, err
}

const getOrderByID = `-- name: GetOrderByID :one
SELECT id, account_id, instrument_id, side, type, quantity, price, status, created_at, filled_quantity
FROM orders
WHERE id = ?
`

func (q *Queries) GetOrderByID(ctx context.Context, id string) (Order, error) {
	row := q.db.QueryRowContext(ctx, getOrderByID, id)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.InstrumentID,
		&i.Side,
		&i.Type,
		&i.Quantity,
		&i.Price,
		&i.Status,
		&i.CreatedAt,
		&i.FilledQuantity,
	)
	return i, err
}

const listOrdersByAccountID = `-- name: ListOrdersByAccountID :many
SELECT id, account_id, instrument_id, side, type, quantity, price, status, created_at, filled_quantity
FROM orders
WHERE account_id = ?
ORDER BY created_at DESC
`

func (q *Queries) ListOrdersByAccountID(ctx context.Context, accountID string) ([]Order, error) {
	rows, err := q.db.QueryContext(ctx, listOrdersByAccountID, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Order
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.InstrumentID,
			&i.Side,
			&i.Type,
			&i.Quantity,
			&i.Price,
			&i.Status,
			&i.CreatedAt,
			&i.FilledQuantity,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateFilledQuantity = `-- name: UpdateFilledQuantity :execresult
UPDATE orders
SET
    filled_quantity = filled_quantity + ?,
    status = CASE
        WHEN filled_quantity + ? >= quantity THEN 'EXECUTED'
        ELSE 'PENDING'
    END
WHERE id = ?
  AND status = 'PENDING'
  AND quantity - filled_quantity >= ?
`

type UpdateFilledQuantityParams struct {
	FilledQuantity   string `json:"filled_quantity"`
	FilledQuantity_2 string `json:"filled_quantity_2"`
	ID               string `json:"id"`
	Quantity         string `json:"quantity"`
}

func (q *Queries) UpdateFilledQuantity(ctx context.Context, arg UpdateFilledQuantityParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateFilledQuantity,
		arg.FilledQuantity,
		arg.FilledQuantity_2,
		arg.ID,
		arg.Quantity,
	)
}
