// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: outbox.sql

package database

import (
	"context"
)

const createOutboxEvent = `-- name: CreateOutboxEvent :exec
INSERT INTO outbox_events (
    id,
    aggregate_id,
    event_type,
    subject,
    payload
)
VALUES (?, ?, ?, ?, ?)
`

type CreateOutboxEventParams struct {
	ID          string `json:"id"`
	AggregateID string `json:"aggregate_id"`
	EventType   string `json:"event_type"`
	Subject     string `json:"subject"`
	Payload     string `json:"payload"`
}

func (q *Queries) CreateOutboxEvent(ctx context.Context, arg CreateOutboxEventParams) error {
	_, err := q.db.ExecContext(ctx, createOutboxEvent,
		arg.ID,
		arg.AggregateID,
		arg.EventType,
		arg.Subject,
		arg.Payload,
	)
	return err
}

const getUnpublishedOutboxEvents = `-- name: GetUnpublishedOutboxEvents :many
SELECT
    id,
    aggregate_id,
    event_type,
    subject,
    payload,
    created_at,
    published_at
FROM outbox_events
WHERE published_at IS NULL
ORDER BY created_at
LIMIT ?
`

func (q *Queries) GetUnpublishedOutboxEvents(ctx context.Context, limit int32) ([]OutboxEvent, error) {
	rows, err := q.db.QueryContext(ctx, getUnpublishedOutboxEvents, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OutboxEvent
	for rows.Next() {
		var i OutboxEvent
		if err := rows.Scan(
			&i.ID,
			&i.AggregateID,
			&i.EventType,
			&i.Subject,
			&i.Payload,
			&i.CreatedAt,
			&i.PublishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markOutboxEventPublished = `-- name: MarkOutboxEventPublished :exec
UPDATE outbox_events
SET published_at = CURRENT_TIMESTAMP
WHERE id = ?
`

func (q *Queries) MarkOutboxEventPublished(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, markOutboxEventPublished, id)
	return err
}
