// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: positions.sql

package database

import (
	"context"
	"database/sql"
	"time"
)

const createPosition = `-- name: CreatePosition :exec
INSERT INTO positions (
    id,
    account_id,
    instrument_id,
    quantity,
    reserved_quantity,
    average_price
)
VALUES (?, ?, ?, ?, ?, ?)
`

type CreatePositionParams struct {
	ID               string `json:"id"`
	AccountID        string `json:"account_id"`
	InstrumentID     string `json:"instrument_id"`
	Quantity         string `json:"quantity"`
	ReservedQuantity string `json:"reserved_quantity"`
	AveragePrice     string `json:"average_price"`
}

func (q *Queries) CreatePosition(ctx context.Context, arg CreatePositionParams) error {
	_, err := q.db.ExecContext(ctx, createPosition,
		arg.ID,
		arg.AccountID,
		arg.InstrumentID,
		arg.Quantity,
		arg.ReservedQuantity,
		arg.AveragePrice,
	)
	return err
}

const executeSellPosition = `-- name: ExecuteSellPosition :execresult
UPDATE positions
SET
    quantity = quantity - ?,
    reserved_quantity = reserved_quantity - ?
WHERE id = ?
  AND reserved_quantity >= ?
  AND quantity >= ?
`

type ExecuteSellPositionParams struct {
	Quantity           string `json:"quantity"`
	ReservedQuantity   string `json:"reserved_quantity"`
	ID                 string `json:"id"`
	ReservedQuantity_2 string `json:"reserved_quantity_2"`
	Quantity_2         string `json:"quantity_2"`
}

func (q *Queries) ExecuteSellPosition(ctx context.Context, arg ExecuteSellPositionParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, executeSellPosition,
		arg.Quantity,
		arg.ReservedQuantity,
		arg.ID,
		arg.ReservedQuantity_2,
		arg.Quantity_2,
	)
}

const getPosition = `-- name: GetPosition :one
SELECT
    id,
    account_id,
    instrument_id,
    quantity,
    reserved_quantity,
    average_price,
    created_at
FROM positions
WHERE account_id = ?
    AND instrument_id = ?
`

type GetPositionParams struct {
	AccountID    string `json:"account_id"`
	InstrumentID string `json:"instrument_id"`
}

type GetPositionRow struct {
	ID               string    `json:"id"`
	AccountID        string    `json:"account_id"`
	InstrumentID     string    `json:"instrument_id"`
	Quantity         string    `json:"quantity"`
	ReservedQuantity string    `json:"reserved_quantity"`
	AveragePrice     string    `json:"average_price"`
	CreatedAt        time.Time `json:"created_at"`
}

func (q *Queries) GetPosition(ctx context.Context, arg GetPositionParams) (GetPositionRow, error) {
	row := q.db.QueryRowContext(ctx, getPosition, arg.AccountID, arg.InstrumentID)
	var i GetPositionRow
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.InstrumentID,
		&i.Quantity,
		&i.ReservedQuantity,
		&i.AveragePrice,
		&i.CreatedAt,
	)
	return i, err
}

const listPositionsByAccountID = `-- name: ListPositionsByAccountID :many
SELECT
    id,
    account_id,
    instrument_id,
    quantity,
    reserved_quantity,
    average_price,
    created_at
FROM positions
WHERE account_id = ?
  AND quantity > 0
ORDER BY created_at DESC
`

type ListPositionsByAccountIDRow struct {
	ID               string    `json:"id"`
	AccountID        string    `json:"account_id"`
	InstrumentID     string    `json:"instrument_id"`
	Quantity         string    `json:"quantity"`
	ReservedQuantity string    `json:"reserved_quantity"`
	AveragePrice     string    `json:"average_price"`
	CreatedAt        time.Time `json:"created_at"`
}

func (q *Queries) ListPositionsByAccountID(ctx context.Context, accountID string) ([]ListPositionsByAccountIDRow, error) {
	rows, err := q.db.QueryContext(ctx, listPositionsByAccountID, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPositionsByAccountIDRow
	for rows.Next() {
		var i ListPositionsByAccountIDRow
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.InstrumentID,
			&i.Quantity,
			&i.ReservedQuantity,
			&i.AveragePrice,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const releasePositionQuantity = `-- name: ReleasePositionQuantity :execresult
UPDATE positions
SET reserved_quantity = reserved_quantity - ?
WHERE id = ?
  AND reserved_quantity >= ?
`

type ReleasePositionQuantityParams struct {
	ReservedQuantity   string `json:"reserved_quantity"`
	ID                 string `json:"id"`
	ReservedQuantity_2 string `json:"reserved_quantity_2"`
}

func (q *Queries) ReleasePositionQuantity(ctx context.Context, arg ReleasePositionQuantityParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, releasePositionQuantity, arg.ReservedQuantity, arg.ID, arg.ReservedQuantity_2)
}

const reservePositionQuantity = `-- name: ReservePositionQuantity :execresult
UPDATE positions
SET reserved_quantity = reserved_quantity + ?
WHERE id = ?
    AND quantity - reserved_quantity >= ?
`

type ReservePositionQuantityParams struct {
	ReservedQuantity string `json:"reserved_quantity"`
	ID               string `json:"id"`
	Quantity         string `json:"quantity"`
}

func (q *Queries) ReservePositionQuantity(ctx context.Context, arg ReservePositionQuantityParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, reservePositionQuantity, arg.ReservedQuantity, arg.ID, arg.Quantity)
}

const updatePosition = `-- name: UpdatePosition :exec
UPDATE positions
SET
    quantity = ?,
    reserved_quantity = ?,
    average_price = ?
WHERE id = ?
`

type UpdatePositionParams struct {
	Quantity         string `json:"quantity"`
	ReservedQuantity string `json:"reserved_quantity"`
	AveragePrice     string `json:"average_price"`
	ID               string `json:"id"`
}

func (q *Queries) UpdatePosition(ctx context.Context, arg UpdatePositionParams) error {
	_, err := q.db.ExecContext(ctx, updatePosition,
		arg.Quantity,
		arg.ReservedQuantity,
		arg.AveragePrice,
		arg.ID,
	)
	return err
}
