// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: positions.sql

package database

import (
	"context"
)

const createPosition = `-- name: CreatePosition :exec
INSERT INTO positions (
    id,
    account_id,
    instrument_id,
    quantity,
    average_price
)
VALUES (?, ?, ?, ?, ?)
`

type CreatePositionParams struct {
	ID           string `json:"id"`
	AccountID    string `json:"account_id"`
	InstrumentID string `json:"instrument_id"`
	Quantity     string `json:"quantity"`
	AveragePrice string `json:"average_price"`
}

func (q *Queries) CreatePosition(ctx context.Context, arg CreatePositionParams) error {
	_, err := q.db.ExecContext(ctx, createPosition,
		arg.ID,
		arg.AccountID,
		arg.InstrumentID,
		arg.Quantity,
		arg.AveragePrice,
	)
	return err
}

const getPosition = `-- name: GetPosition :one
SELECT
    id,
    account_id,
    instrument_id,
    quantity,
    average_price,
    created_at
FROM positions
WHERE account_id = ?
    AND instrument_id = ?
`

type GetPositionParams struct {
	AccountID    string `json:"account_id"`
	InstrumentID string `json:"instrument_id"`
}

func (q *Queries) GetPosition(ctx context.Context, arg GetPositionParams) (Position, error) {
	row := q.db.QueryRowContext(ctx, getPosition, arg.AccountID, arg.InstrumentID)
	var i Position
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.InstrumentID,
		&i.Quantity,
		&i.AveragePrice,
		&i.CreatedAt,
	)
	return i, err
}

const listPositionsByAccountID = `-- name: ListPositionsByAccountID :many
SELECT
    id,
    account_id,
    instrument_id,
    quantity,
    average_price,
    created_at
FROM positions
WHERE account_id = ?
  AND quantity > 0
ORDER BY created_at DESC
`

func (q *Queries) ListPositionsByAccountID(ctx context.Context, accountID string) ([]Position, error) {
	rows, err := q.db.QueryContext(ctx, listPositionsByAccountID, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Position
	for rows.Next() {
		var i Position
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.InstrumentID,
			&i.Quantity,
			&i.AveragePrice,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePosition = `-- name: UpdatePosition :exec
UPDATE positions
SET
    quantity = ?,
    average_price = ?
WHERE id = ?
`

type UpdatePositionParams struct {
	Quantity     string `json:"quantity"`
	AveragePrice string `json:"average_price"`
	ID           string `json:"id"`
}

func (q *Queries) UpdatePosition(ctx context.Context, arg UpdatePositionParams) error {
	_, err := q.db.ExecContext(ctx, updatePosition, arg.Quantity, arg.AveragePrice, arg.ID)
	return err
}
